// 类型定义
export const CookieType = {
  IMPORTANT_URGENT: 'IMPORTANT_URGENT',
  IMPORTANT_NOT_URGENT: 'IMPORTANT_NOT_URGENT',
  URGENT_NOT_IMPORTANT: 'URGENT_NOT_IMPORTANT',
  NOT_IMPORTANT_NOT_URGENT: 'NOT_IMPORTANT_NOT_URGENT',
  MUMBLING: 'MUMBLING'
};
